/*
ALTER TABLE `mymeteo`.`samples`
ADD COLUMN `report_format` VARCHAR(128) NULL DEFAULT NULL AFTER `sensor_id` ;
*/
update mymeteo.samples set report_format='I like to be clean, that\'s why I cleaned my teeth in the morning.' where id='54353cacaf2aa';
update mymeteo.samples set report_format='Do you think cleaning my teeth is my priority? No! I have other things to do in life!' where id='54353cacaf337';
update mymeteo.samples set report_format='Despite all the bad press around it garlig is healthy and I like it, so I ate some lately' where id='54353cc690402';
update mymeteo.samples set report_format='Nothing is more precious to me than my fresh breath. No garlig for me!' where id='54353cc69048f';
update mymeteo.samples set report_format='Unfortunatly I ran out of toilet paper... But no panic I always have a 5€ bank not for that case' where id='54353d35dbf12';
update mymeteo.samples set report_format='I\'m causious, as you know, I always check the toilet paper before taking a grap. I never ran out of it!' where id='54353d35dbf9f';
update mymeteo.samples set report_format='God damn. I wasted I don\'t know how many hours to find a parking spot!' where id='54353d7e0e378';
update mymeteo.samples set report_format='I was so lucky thansks god, I found a parking spot immediately' where id='54353d7e0e404';
update mymeteo.samples set report_format='Again I was recovering from an hangover the day before ...' where id='54353da6d5b73';
update mymeteo.samples set report_format='For a change I didn\'t have an hangover the day before' where id='54353da6d5bff';
update mymeteo.samples set report_format='That day I had a terrible hangover' where id='54353dc6698ca';
update mymeteo.samples set report_format='That day I didn\'t have an hangover' where id='54353dc669954';
update mymeteo.samples set report_format='That day I took a lotery ticket.' where id='54353de177f64';
update mymeteo.samples set report_format='That day I didn\'t take a lotery ticket' where id='54353de177ff0';
update mymeteo.samples set report_format='That day I blow some red spot on my face. The mirrow was full of white spot' where id='54353e1b60e7e';
update mymeteo.samples set report_format='That day my face was clean and the mirror too!' where id='54353e1b60f08';
update mymeteo.samples set report_format='Terrible things happend to me, I forget my Baby\'s birthday. I had to be nice ofr an hour to be forgiven...' where id='54353e4067385';
update mymeteo.samples set report_format='Obviously I didn\'t forget the birthday of my dear Baby! I have a calendar to use it!' where id='54353e4067411';
update mymeteo.samples set report_format='I was my birthday! weither or not I celebrated it, it is always unhealthy' where id='54353e5ee0579';
update mymeteo.samples set report_format='It was not my birthday, so nothing special...' where id='54353e5ee0607';
update mymeteo.samples set report_format='My poo is perfect. I\'m in good condition' where id='54353e8ea0538';
update mymeteo.samples set report_format='I\'m not feeling too good. My poo is not nice to see...' where id='54353e8ea05c5';
update mymeteo.samples set report_format='I had a weakness for a beggar and I gave 20 cents. ' where id='54353ea94cb90';
update mymeteo.samples set report_format='They can show me their little pupy or kids I don\'t give to beggars' where id='54353ea94cc24';
update mymeteo.samples set report_format='It is nice because a beautifull stranger smilled at me that day.' where id='54353ed5e4e39';
update mymeteo.samples set report_format='That was not a good day because no beautifull stranger smiled at me.' where id='54353ed5e4ec6';
update mymeteo.samples set report_format='I saw a very beautifull stranger. It is always good for the hope!' where id='54353f03cff1b';
update mymeteo.samples set report_format='I only see ugly people.' where id='54353f03cffa9';
update mymeteo.samples set report_format='It was raining and I forgot my water proof shoes. Shity life!' where id='54353f3f3fd2a';
update mymeteo.samples set report_format='Nothing can surprise me, even less the rain! I always have waterproof shoes on me!' where id='54353f3f3fdb4';
update mymeteo.samples set report_format='What a feeling! I said no to my boss!' where id='54353f65a14f8';
update mymeteo.samples set report_format='I couldn\'t say no to my boss and I felt terrible' where id='54353f65a1588';
update mymeteo.samples set report_format='It is bad for my wallet: a new tigger shop openned near by...' where id='54353fc080854';
update mymeteo.samples set report_format='At least my wallet is not threatned by a tigger shop near by!' where id='54353fc0808e1';
update mymeteo.samples set report_format='An other weekend away is terrible for my wallet' where id='543540318251b';
update mymeteo.samples set report_format='A weekend home is not bad for my wallet point of view.' where id='54354031825a6';
update mymeteo.samples set report_format='It is normal for me to change my underwear in the morning, and my Baybay appreciate it!' where id='5437c0365d65a';
update mymeteo.samples set report_format='I didn\'t change my underwear everyday... Will I go to hell for that?' where id='5437c0365d6ea';
update mymeteo.samples set report_format='I prefer cat, they cost less.' where id='5437c05f0c0b8';
update mymeteo.samples set report_format='I prefer dog. I\'m rich enough!' where id='5437c05f0c147';
update mymeteo.samples set report_format='I scored yesterday! And I didn\'t pay a penny!' where id='5437c08d1b5bf';
update mymeteo.samples set report_format='I didn\'t score but I didn\'t spend a penny either...' where id='5437c08d1b64e';
update mymeteo.samples set report_format='I\'m planning to go to bars. I give you money, you give me heaven!' where id='5437c0c545603';
update mymeteo.samples set report_format='I\'m planning to exercice a bit. I have nothing to add!' where id='5437c0c5456d8';
update mymeteo.samples set report_format='I only need a new pair of socks' where id='5437c0f7045b1';
update mymeteo.samples set report_format='I really need a new trouser. It will cost me all my economies' where id='5437c0f704647';
update mymeteo.samples set report_format='I\'m tired because I let my seat to a pregnant woman' where id='5437c12a92160';
update mymeteo.samples set report_format='I feel terrific, I\'m rested and my back don\'t hurt. I did well not to let my seat to that granny!' where id='5437c12a921f1';
update mymeteo.samples set report_format='They say it is good luck, but I lost money somehow because I step into a dog poo' where id='543d141bb0ec1';
update mymeteo.samples set report_format='Thanks lord I didn\'t step into dog poo and I didn\'t waste time=money to clean my shoes!' where id='543d141bb0f45';
update mymeteo.samples set report_format='I met my neighboor after an evening at the pub. Their eyes were guns!' where id='543d14cd0aa1b';
update mymeteo.samples set report_format='My neighboor are lucky to have me. I\'m the perfect neighboor.' where id='543d14cd0aaa3';
update mymeteo.samples set report_format='Nooo! I found a grey hair in my hairs today! I\'ll have to cover it and it will cost me a lot!' where id='543f90402ac15';
update mymeteo.samples set report_format='Luckily I don\'t have to spend a fortune to cover my white hair yet!' where id='543f90402ad2b';
update mymeteo.samples set report_format='Don\'t repeat but I farted in bed. ' where id='543f912a7be95';
update mymeteo.samples set report_format='I\'m proud to say that I didn\'t fart in bed.' where id='543f912a7bf51';
update mymeteo.samples set report_format='Sorry but I pee outside the bowl sometimes. Nobody is perfect!' where id='543fbe3aeafb5';
update mymeteo.samples set report_format='Something no one can reproach me is to pee outside the bowl!' where id='543fbe3aeb047';
update mymeteo.samples set report_format='Of course I take the garbage to the container. I help at home!' where id='543fbe6adf2e3';
update mymeteo.samples set report_format='I have no time to take the garbage to the container. I am a busy person. Sorry!' where id='543fbe6adf369';
update mymeteo.samples set report_format='I was a wonderfull day for my hair. They obey!' where id='544104a9595cb';
update mymeteo.samples set report_format='I wished I was bold. My hair were having a revolution... ' where id='544104a959de0';
update mymeteo.samples set report_format='I smoked like a fireman.' where id='5453b54e8b7f6';
update mymeteo.samples set report_format='I didn\'t smoke.' where id='5453b54e8b854';
update mymeteo.samples set report_format='I feel lighter! I quit my job!' where id='5453b60fe4807';
update mymeteo.samples set report_format='I would feel better if I could quit my job but I have to pay the bills...' where id='5453b60fe4863';
update mymeteo.samples set report_format='I ate lots of fat and salt lately and that\'s the way I like it!' where id='5453b64cc791b';
update mymeteo.samples set report_format='I eat green and I feel good!' where id='5453b64cc7975';
update mymeteo.samples set report_format='OMG! I was fired! Me! Fired! I\'m supposed to be the best! Mum did you lie to me?' where id='5453b67a11912';
update mymeteo.samples set report_format='I should play lotery because I was not fired yet.' where id='5453b67a1196b';
update mymeteo.samples set report_format='last time I was at the hairdresser was a year ago!' where id='54577b0e6007a';
update mymeteo.samples set report_format='I cut my hair and I look better!' where id='54577b0e600fd';
update mymeteo.samples set report_format='If I\'m not well in my skin it is because my parents didn\'t let me watch tv when I was younger' where id='54577b601df2d';
update mymeteo.samples set report_format='Despite the fact that my parents didn\'t let me watch tv when I was kid, I\'m a fine adult now!' where id='54577b601dfb1';
update mymeteo.samples set report_format='as usual my compost basket is smelly and the meeting point of all the flies in the neigborhood.' where id='54577b9bf296f';
update mymeteo.samples set report_format='somebody well informed told me about compost today. I\'ll think about it next time.' where id='54577b9bf2a61';
update mymeteo.samples set report_format='I take care of everything. My plant is green like the amazonian forest' where id='54577becc5a82';
update mymeteo.samples set report_format='I can\'t even take care of my green plant. It is all dry and yellow...' where id='54577becc5f10';
update mymeteo.samples set report_format='I always leave a tip' where id='5459eb5f8a4be';
update mymeteo.samples set report_format='I never leave a tip' where id='5459eb5f8a543';
update mymeteo.samples set report_format='I\'m zen, I didn( spend much time in traffic' where id='5459ebc40bbde';
update mymeteo.samples set report_format='If I would count the amount of time I spend in traffic I would faint' where id='5459ebc40bcd4';
update mymeteo.samples set report_format='since I have 2 legs I walked my 30 minutes a day' where id='5459ec0ff24cb';
update mymeteo.samples set report_format='since I have a car I used it instead of my 2 legs' where id='5459ec0ff25d7';
update mymeteo.samples set report_format='If I acted like a cop it was because I needed to know. ' where id='5459ece28489e';
update mymeteo.samples set report_format='We are in harmony. No need to play cops (or only in bed) with my Baby!' where id='5459ece284923';
update mymeteo.samples set report_format='I had several coffee breaks. It is important to slow down!' where id='5459ed2511db0';
update mymeteo.samples set report_format='I had no time to take a coffee break. I\'m very stressed!' where id='5459ed2511e43';
update mymeteo.samples set report_format='I say a good movie. It changed my mind set. I forgot my worries' where id='5459ed5fdf779';
update mymeteo.samples set report_format='If only I could see a good movie to think about something else time to times!' where id='5459ed5fdf7fe';
update mymeteo.samples set report_format='I was dancing on one of my favorite song' where id='5459eda7cdc25';
update mymeteo.samples set report_format='I hear only crapy songs.' where id='5459eda7cdcdd';
update mymeteo.samples set report_format='One more time I throw a roll of toilet paper in the bowl full of crap... I had to take it back. Beurk!' where id='5459f6b3e73a5';
update mymeteo.samples set report_format='I\'m not the kind of person to drop a roll of toilet paper in a bowl full of crap!' where id='5459f6b3e74ac';
update mymeteo.samples set report_format='I cleaned the bathroom and the shower. No mushroom farm there! It is shining and fresh!' where id='5459f7a645724';
update mymeteo.samples set report_format='I like my bathroom with mushrom.' where id='5459f7a6457a6';
update mymeteo.samples set report_format='I changed my bed sheets. It smells so good!' where id='5459f7e7c406e';
update mymeteo.samples set report_format='I was thinking to change my bed sheets but then I thought: why would I do that?!' where id='5459f7e7c4164';
update mymeteo.samples set report_format='I\'m eating well, I ate my 5 vegetables a day, and they were not even in can!' where id='545b89031b877';
update mymeteo.samples set report_format='Screw what they say on tv. I won\'t eat 5 vegetables a day. I like meat and basta!' where id='545b89031b8fd';
update mymeteo.samples set report_format='For the sake of our relationship I tried to help my Baybay. Things has to change!' where id='545b895955868';
update mymeteo.samples set report_format='I love my Baybay\'s way to handle things even if I wouldn\'t do it like that!' where id='545b8959558f1';
update mymeteo.samples set report_format='I start to feel like at school, my baybay tried to help me again... I\'m not handicaped' where id='545b89be0bf6e';
update mymeteo.samples set report_format='My baybay let me do my way. I love it!' where id='545b89be0bff0';
update mymeteo.samples set report_format='I had to say no to my Baby. I was firm but fair as usual.' where id='545b8a289f511';
update mymeteo.samples set report_format='My Baybay ask me to jump the bridge I jump the bridge! I\'m in love you know...' where id='545b8a289f5bd';
update mymeteo.samples set report_format='I made a new friend!' where id='545b9890df424';
update mymeteo.samples set report_format='No new friend on sight. Still hanging with the same old gang' where id='545b9890df52d';
update mymeteo.samples set report_format='I had my lunch box today. I saved lots of cash!' where id='545cc3f76bd9b';
update mymeteo.samples set report_format='I didn\'t have my lunch box so I had to spend half of my salary in the restaurant' where id='545cc3f76be1e';
update mymeteo.samples set report_format='All my money goes to the gazoline...' where id='545cc43c08da7';
update mymeteo.samples set report_format='I spare lot\'s of money because I don\'t take a car to go to work!' where id='545cc43c08e1f';
update mymeteo.samples set report_format='I\'m an educated and reponsible person so I think of the future. I sort my garbage.' where id='545cc4fb53874';
update mymeteo.samples set report_format='Hell after me. I put all my garbage in the same bag!' where id='545cc4fb538f9';
