---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8000}]
  - ["forwarded_port", {guest: 81, host: 8080}]
  - ["forwarded_port", {guest: 82, host: 8082}]
  - ["forwarded_port", {guest: 443, host: 8443}]
  - ["forwarded_port", {guest: 8080, host: 8888}]
  - ["forwarded_port", {guest: 10081, host: 8010}]
  - ["forwarded_port", {guest: 3306, host: 8006}]
  - ["forwarded_port", {guest: 9200, host: 8092}]
  - ["forwarded_port", {guest: 1337, host: 8137}]
  synced_folders:
  - [".", "/vagrant"]

provisioner:
  name: chef_zero
  require_chef_omnibus: latest
  data_bags_path: resources/data_bags

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
    
suites:
  - name: default
    run_list: 
    - recipe[apt]
    - recipe[build-essential]
    - recipe[networking_basic]
    - recipe[zend-server]
    - recipe[zend-server::xdebug]
    - recipe[apache::apache234]
    - recipe[mymeteodb]
    attributes: 
     zend-server:
       php_version: 5.4
       
  - name: zs7
    run_list: 
    - recipe[apt]
    - recipe[build-essential]
    - recipe[networking_basic]
    - recipe[zendphp]
    - recipe[apache]
    - recipe[mymeteodb]
    - recipe[ruby]
    - recipe[mm-elasticsearch]
    attributes: 
      kibana:
        version: 3.0.0
        apache:
          port: 82
      java: 
        jdk_version: 7	
      elasticsearch:
        version: 1.3.4 
        mlockall: false
        nginx:
          allow_cluster_api : true
        monit:
          notify_email : julien_desbois@hotmail.com
          mail_format  : 
            from: monit@mindmeteo.com
            subject: "[monit] $SERVICE $EVENT on $HOST"
            message: "$SERVICE $ACTION: $DESCRIPTION"
            
  - name: node
    run_list: 
    - recipe[apt]
    - recipe[build-essential]
    - recipe[networking_basic]
    - recipe[mymeteodb]
    - recipe[ruby]
    - recipe[mm-elasticsearch]
    - recipe[js::sails]
    - recipe[js::bower]
    attributes: 
      kibana:
        version: 3.0.0
        apache:
          port: 82
      java: 
        jdk_version: 7	
      elasticsearch:
        version: 1.3.4 
        mlockall: false
        nginx:
          allow_cluster_api : true
        monit:
          notify_email : julien_desbois@hotmail.com
          mail_format  : 
            from: monit@mindmeteo.com
            subject: "[monit] $SERVICE $EVENT on $HOST"
            message: "$SERVICE $ACTION: $DESCRIPTION"