---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8080}]
  - ["forwarded_port", {guest: 10081, host: 8081}]
  - ["forwarded_port", {guest: 3306, host: 8006}]
  synced_folders:
  - [".", "/vagrant"]

provisioner:
  name: chef_solo
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-12.04
    
suites:
  - name: default
    run_list: 
    - recipe[apt]
    - recipe[build-essential]
    - recipe[networking_basic]
    - recipe[zend-server]
    - recipe[apache]
    - recipe[mymeteodb]
    attributes: 
     zend-server:
       php_version: 5.4