language: node_js
node_js:
- '0.10'
services:
- elasticsearch
before_install:
- npm install -g grunt-cli bower karma
before_script:
- mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS mymeteo_test DEFAULT CHARACTER SET
  utf8 COLLATE utf8_unicode_ci;'
- cat test/mysql_add_user.sql | mysql -uroot
- bower install
- grunt build
script:
- grunt test
- npm test
deploy:
  provider: codedeploy
  access_key_id: AKIAJNGSIYB7XZROIG3A
  secret_access_key:
    secure: QfI8RHEsLcu0+fRys591FcerGQUAfHPzZ8NuMlgETyfxgPQPAKLkpmUKs34VO1XTn2aM77yqXpSYoTHEKhuwc76aZEyFbXt+DOMLJQYgbODZR/fmYAn3Nsp761oWipkCcwdrXyIITeDg3+zV0fPULUhBB2GCc8O7kkl8TbjUfqM=
  application: MindMeteoProd
  deployment_group: MindMeteoProd
  on:
    repo: devitito/mymindmeteo
    branch: node
