language: node_js
node_js:
  - "0.10"
services:
  - elasticsearch
before_install:
  - npm install -g grunt-cli bower karma

before_script:
  - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS mymeteo_test DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;'
  - 'cat test/mysql_add_user.sql | mysql -uroot'
  - 'bower install'
  - grunt build
script:
  - grunt test
  - npm test
