version: 0.0
os: linux
files:
  - source: /index.html
    destination: /home/ubuntu/mindmeteo
hoocks:
  ApplicationStop:
    - location: scripts/stopforever.sh
      runas: root
  BeforeInstall:
    - location: scripts/cleanBerforeInstall.sh
      runas: root
  AfterInstall:
    - location: scripts/afterinstall.sh
      runas: root
  ApplicationStart:
    - location: scripts/restartforever.sh
      runas: root
