version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/mindmeteo
hoocks:
  ApplicationStop:
    - location: scripts/stopforever.sh
      runas: root
  BeforeInstall:
	  - location: scripts/cleanBeforeInstall.sh
      runas: root
  AfterInstall:
    - location: scripts/restartforever.sh
      runas: root
