version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/mindmeteo
hooks:
  ApplicationStop:
    - location: scripts/stopforever.sh
      runas: root
    - location: scripts/cleanbeforeinstall.sh
      runas: root
  ApplicationStart:
    - location: scripts/restartforever.sh
      runas: root
