version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/mindmeteo
permissions:
  - object: /home/ubuntu/mindmeteo/scripts
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hoocks:
  BeforeInstall:
    - location: scripts/stopforever.sh
      runas: root
    - location: scripts/cleanBeforeInstall.sh
      runas: root
  AfterInstall:
    - location: scripts/restartforever.sh
      runas: root
