version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/mindmeteo
hoocks:
  AfterInstall:
    - location: scripts/stopforever.sh
      runas: root
  ApplicationStart:
    - location: scripts/restartforever.sh
      runas: root
