version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/mindmeteo
permissions:
   - object: /home/ubuntu/mindmeteo
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
