source "https://supermarket.getchef.com"

cookbook 'apt'
cookbook 'build-essential'
cookbook 'networking_basic'
cookbook 'apache2'
cookbook 'zend-server'
cookbook 'java'
cookbook 'elasticsearch', '=0.3.10'
cookbook 'monit', '=0.7.5'
cookbook 'kibana', '=0.1.8'
cookbook 'apache' , path: 'resources/cookbooks/apache'
cookbook 'mymeteodb' , path: 'resources/cookbooks/mymeteodb'
cookbook "mysql", '= 5.4.4'
cookbook "database", '= 2.3.1'
cookbook "mysql-chef_gem", '= 0.0.5'
cookbook 'zendphp' , path: 'resources/cookbooks/zendphp'
cookbook 'ruby' , path: 'resources/cookbooks/ruby'
cookbook 'mm-elasticsearch', path: 'resources/cookbooks/mm-elasticsearch'
cookbook 'js', path: 'resources/cookbooks/js'
