<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
    <h4 class="modal-title" id="sensorModalLabel">Contribute with your own sensors</h4>
</div>
<?php 
	if (!isset($message)) {
		$sensorform->prepare();
		echo $this->form()->openTag($sensorform);
	}
?>
<div class="modal-body">
<?php 
	if (!isset($message)) {
		echo '<div id="errormsg"></div>';
		echo '<h3>Sensor description</h3>';
		echo '<div class="form-group">'.$this->formRow($sensorform->get('label')).'</div>';
		echo '<div class="form-group">'.$this->formRow($sensorform->get('topic')).'</div>';
		echo '<h3>Positive sample</h3>';
		echo '<div class="row">';
		echo '<div class="form-group col-md-5">'.$this->formRow($sensorform->get('answerPositive')).'</div>';
		echo '<div class="form-group col-md-1"></div>';
		echo '<div class="form-group col-md-6" style="margin-top: 10px;"><span style="margin-right: 15px;">Value:</span>'.$this->formRow($sensorform->get('answerPositiveValue'));
		echo '</div></div>';
		echo '<h3>Negative sample</h3>';
		echo '<div class="row">';
		echo '<div class="form-group col-md-5">'.$this->formRow($sensorform->get('answerNegative')).'</div>';
		echo '<div class="form-group col-md-1"></div>';
		echo '<div class="form-group col-md-6" style="margin-top: 10px;"><span style="margin-right: 15px;">Value:</span>'.$this->formRow($sensorform->get('answerNegativeValue'));
		echo '</div></div>';
	}
	else {
		echo $message;
	}
?>
</div>
<div class="modal-footer">
<?php
	if (!isset($message)) {
		echo $this->formSubmit($sensorform->get('submitsensor'));
		echo $this->formRow($sensorform->get('dismiss'));
	}
	else {
		echo "<button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>";
	}
?>
</div>
<?php 
	if (!isset($message))
		echo $this->form()->closeTag(); 
?>