<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/"></a>
        </div>
        <div class="navbar-collapse collapse">
        	<div class="navbar-right">
	        	<a class="btn btn-meteo navbar-btn " href="/join" role="button">Register</a>
	        	<a class="btn btn-meteo navbar-btn " href="/login" role="button">Sign in</a>
	        </div>
        </div><!--/.navbar-collapse -->
      </div>
</div>