<script type="text/javascript" src="/js/jscroll/jquery.jscroll.min.js"></script>

<h1>Weather reports</h1>

<div class="scroll" data-ui="jscroll-default">
	<div class="jscroll-inner">
			<div class="item" style="padding-left: 5px;">
				<div class="row accordion-toggle" data-toggle="collapse" data-target="#msg1">
					<div class="col-md-2">
						Mama
					</div>
					<div class="col-md-5">
						It's all right ma, I'm only bleeding
					</div>
					<div class="col-md-2">
						12 June 2014
					</div>
					<div class="col-md-2">
						An independant meteologist
					</div>
					<div class="col-md-1">
						<span class="glyphicon glyphicon-chevron-down"></span>
					</div>
					<br>
				</div>
				<div class="row" style="padding-left: 20px; padding-right: 20px;">
					<div class="accordian-body collapse" id="msg1">
						<br>Mimimi, mimii miii mii mimii ...
						<hr>
			        </div>
	    		</div>
    		</div>
    		<div class="item" style="padding-left: 5px;">
	    		<div class="row accordion-toggle" data-toggle="collapse" data-target="#msg2">
					<div class="col-md-2">
						A friend
					</div>
					<div class="col-md-5">
						Dude you'll never guess who exciting is my life
					</div>
					<div class="col-md-2">
						12 June 2014
					</div>
					<div class="col-md-2">
						MindMeteo
					</div>
					<div class="col-md-1">
						<span class="glyphicon glyphicon-chevron-down"></span>
					</div>
				</div>
				<div class="row" style="padding-left: 20px; padding-right: 20px;">
					<div class="accordian-body collapse" id="msg2">
						<br>Mimimi, mimii miii mii mimii Mimimi, mimii miii mii mimii .Mimimi, mimii miii mii mimii .Mimimi, mimii miii mii mimii ...<br>
			                	Mimimi, mimii miii mii mimii ....
			            <hr>
			        </div>
	    		</div>
    		</div>
    		<div class="item" style="padding-left: 5px;">
	    		<div class="row accordion-toggle" data-toggle="collapse" data-target="#msg3">
					<div class="col-md-2">
						Mama
					</div>
					<div class="col-md-5">
						More news for you. I'm a great son isn't it?
					</div>
					<div class="col-md-2">
						13 June 2014
					</div>
					<div class="col-md-2">
						Mad Meteo
					</div>
					<div class="col-md-1">
						<span class="glyphicon glyphicon-chevron-down"></span>
					</div>
				</div>
				<div class="row" style="padding-left: 20px; padding-right: 20px;">
					<div class="accordian-body collapse" id="msg3">
						<br>Mimimi, mimii miii mii mimii Mimimi, mimii miii mii mimii .Mimimi, mimii miii mii mimii .Mimimi, mimii miii mii mimii ...<br>
			                	Mimimi, mimii miii mii mimii ....
			            <hr>
			        </div>
	    		</div>
    		</div>
	    	<div class="next text-center"><a href="/page2.html">next</a></div>
	</div>
</div>






<script>
$(document).ready(function() {
	$( ".jscroll-inner" ).on( "click", ".accordion-toggle", function() {
		$(this).find("span").toggleClass('glyphicon-chevron-down glyphicon-chevron-up');
	});

	$( ".jscroll-inner" ).on( "mouseover", ".item", function() {
		$(this).css("background-color","#f2f1f0");
	});

	$( ".jscroll-inner" ).on( "mouseout", ".item", function() {
		$(this).css("background-color","white");
	});

	$('[data-ui="jscroll-default"]').jscroll({
		autoTrigger: false,
		debug: true,
		});
});
 </script>




		