<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
    <h4 class="modal-title" id="sensorModalLabel">Contribute with your own sensors</h4>
</div>
<?php 
	if (!isset($message))
		echo $this->form()->openTag($sensorform);?>
<div class="modal-body">
<?php 
	if (!isset($message)) {
		foreach ($sensorform as $element) {
			if (($element->getName() !== 'submitsensor') && ($element->getName() !== 'dismiss')) {
				echo '<div class="form-group">
				' . $this->formElement($element) . '
				</div>';
			}
		}
	}
	else {
		echo $message;
	}
?>
</div>
<div class="modal-footer">
<?php
	if (!isset($message)) {
		foreach ($sensorform as $element) {
			if (($element->getName() == 'submitsensor') || ($element->getName() == 'dismiss')) {
				echo $this->formElement($element);
			}
		}
	}
	else {
		echo "<button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>";
	}
?>
</div>
<?php 
	if (!isset($message))
		echo $this->form()->closeTag(); 
?>
