<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
    <h4 class="modal-title" id="analyseModalLabel">Contribute with your own weather analyse</h4>
</div>
<div class="modal-body">
	<h1><?php echo $this->translate('Sorry, it is not yet possible to send us your weather analyse. Soon!') ?></h1>
</div>
<div class="modal-footer">
	<button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>
</div>