<!-- Le styles -->
 <?php echo $this->headLink()
 				->prependStylesheet('/css/morris.css')
 				->prependStylesheet('/css/slider.css')
 				->prependStylesheet($this->basePath() . '/btvalidator/dist/css/bootstrapValidator.min.css')
 ?>

<!-- Scripts -->
<?php echo $this->headScript()
				->prependFile('/js/jscroll/jquery.jscroll.min.js')
        		->prependFile('/js/raphael-min.js')
				->prependFile('/js/morris.min.js')
				->prependFile('/js/bootstrap-slider.js')
				->prependFile($this->basePath() . '/btvalidator/dist/js/bootstrapValidator.min.js');
?>

<!-- Sensor Modal -->
<div style="display: none;" id="sensormodal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="sensorModalLabel" aria-hidden="true">
	<div class="modal-dialog">
      <div id="sensormodal-content" class="modal-content">

      </div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div>

<!-- Test Modal -->
<div style="display: none;" id="measurementmodal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="measurementModalLabel" aria-hidden="true">
	<div class="modal-dialog">
      <div id="measurementmodal-content" class="modal-content">

      </div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div>

<!-- Analyse Modal -->
<div style="display: none;" id="analysemodal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="analyseModalLabel" aria-hidden="true">
	<div class="modal-dialog">
      <div id="analysemodal-content" class="modal-content">

      </div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div>

<!-- Please wait modal -->
<div style="display: none;" id="waitmodal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="waitModalLabel" aria-hidden="true">
	<div class="modal-dialog">
      <div class="modal-content">
      	<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
		    <h4 class="modal-title" id="waitModalLabel"><?php echo $this->translate('We are processing your request')?></h4>
		</div>
		<div class="modal-body">
			<div><?php echo $this->translate('Please wait...')?></div>
		</div>
      </div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div>


<div class="navbar-wrapper">
	<div class="container">
		<div class="navbar navbar-default navbar-fixed-top" role="navigation">
		  <div class="container">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="brand img-circle" href="/"></a>
		    </div>
		
		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <form class="navbar-form navbar-left" role="search">
		        <div class="form-group">
		          <input type="text" class="form-control" placeholder="Search">
		        </div>
		        <button type="submit" class="btn btn-meteo">Submit</button>
		      </form>
		      <ul class="nav navbar-nav navbar-right">
		      <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Contribute <span class="caret"></span></a>
		          <ul class="dropdown-menu" role="menu">
		            <li><a href="#" id="sensor-contribution-button">Send us a new sensor</a></li>
		            <li><a href="#" id="anaylse-contribution-button">Send us a new weather analyse</a></li>
		          </ul>
		        </li>
		        <li>
		          <a href="#" class="glyphicon glyphicon-map-marker tooltip-link" id="sensor-test-button" data-toggle="tooltip" data-placement="left" title="Record meteo data of your mind"></a>
		        </li>
		        <li>
		          <a href="#" class="glyphicon glyphicon-envelope tooltip-link"  data-toggle="tooltip" data-placement="left" title="Generate a weather report of your mind"></a>
		        </li>
		        <li>
		          <a href="/mind/logout" class="glyphicon glyphicon-log-out"></a>
		        </li>
		      </ul>
		      
		      	
		      
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
	    <div class="col-md-3">
	        <a href="'/mind/account' ?>">
	        	<img alt="" height="230" width="230" src="/img/icons/placeholder.png">
	        </a>
			<br><br>
			<table class="table">
				<tr>
					<h4 id="mindname"><?php echo $this->mind->getName() ?>	</h4>
				</tr>
				<tr>
					<td>
						<span class="glyphicon glyphicon-time"></span>
						<span>Joined on </span>
						<time>
							<?php 
								echo $this->dateFormat(
								    $this->mind->getJoindate(),
								    IntlDateFormatter::LONG, // date
								    IntlDateFormatter::NONE, // time
								    $this->mind->getLocale());
							?>
						</time>
					</td>
				</tr>
				<tr>
					<td>
						<div class="row">
						<div class="col-md-2">
					    	<p><span id="nbtest" class="badge">-</span></p>
					    	<p><span id="nbsunny" class="badge">-</span></p>
					    	<p><span id="nbrainy" class="badge">-</span></p>
					    </div>
					    <div class="col-md-10">
					    	<p>Test completed </p>
					    	<p>Sunny days </p>
					    	<p>Rainy days </p>
					    </div>
					</div>
					</td>
				</tr>
				
			</table>
	    </div>
	    
	    <div class="col-md-9">
		     <ul id="myTab" class="nav nav-tabs nav-justified" role="tablist">
		      <li class="active"><a href="#climat" role="tab" data-toggle="tab">Climat</a></li>
		      <li class=""><a href="#reports" role="tab" data-toggle="tab">Reports</a></li>
		      <li class=""><a href="#data" role="tab" data-toggle="tab">Measurements</a></li>
		      <li class=""><a href="#alerts" role="tab" data-toggle="tab">Alerts</a></li>
		      <li class=""><a href="#friends" role="tab" data-toggle="tab">Similar minds</a></li>
		    </ul>
		    <div id="myTabContent" class="tab-content">
		      <div class="tab-pane fade active in text-center" id="climat">
		      		<br>
		      		<span class="glyphicon glyphicon-refresh spin loading-indicator"></span><span class="loading-indicator"><?php echo $this->translate('  Loading...')?></span>
					<div id="meteochart" style="height: 400px;"></div>
		      </div>
		      <div class="tab-pane fade" id="reports">
				<?php echo $this->partial('partials/reports-list'); ?>
		      </div>
		      <div class="tab-pane fade" id="data">
		      	<p>meteo raw data questions already answered (with answer and date)</p>
		      </div>
		       <div class="tab-pane fade" id="alerts">
		      	<p>List of marking events, or events to come in the agenda (big party, date, pay day...)</p>
		      	<p>(storms, take a day off: great sun)</p>
		      </div>
		      <div class="tab-pane fade" id="friends">
		      	<p>friends (following the same meteo trends) Similar meteo systems</p>
		      </div>
		    </div>
      	</div>
	</div>   
</div>

<script>

function updateNbCompletedTest()
{
	$.ajax({
    	type: 'GET',
        url: "/mind/sensors/completed/count", 
        cache: false,
        success: function(msg){
        	$('#nbtest').text(msg)
        },
        error: function(xhr, status, error) {
        	$('#nbtest').text('-')
        }
    });
}

function updateNbSunnyDays()
{
	$.ajax({
    	type: 'GET',
        url: "/mind/days/sunny", 
        cache: false,
        success: function(msg){
        	$('#nbsunny').text(msg)
        },
        error: function(xhr, status, error) {
        	$('#nbsunny').text('-')
        }
    });
}

function updateNbRainyDays()
{
	$.ajax({
    	type: 'GET',
        url: "/mind/days/rainy", 
        cache: false,
        success: function(msg){
        	$('#nbrainy').text(msg)
        },
        error: function(xhr, status, error) {
        	$('#nbrainy').text('-')
        }
    });
}

function errorModal(msg)
{
	return "<div class='modal-header'><button type='button' class='close' data-dismiss='modal'><span aria-hidden='true'>×</span><span class='sr-only'>Close</span></button>"
	+ "<h4 class='modal-title'>Error</h4><div class='modal-body'>"+ msg + "</div><div class='modal-footer'><button type='button' class='btn btn-default' data-dismiss='modal'>Close</button></div>"
}

function updateMeteoChart()
{
	$.ajax({
    	type: 'GET',
        url: "/mind/meteochart", 
        data: $("#mindname").text(),
        cache: false,
        beforeSend: function(xhr,opt){
        	$('.loading-indicator').show();
        	$('.loading-indicator').addClass('spin');
        	$('#meteochart').empty();
        },
        success: function(msg){
            if ($.isEmptyObject(msg)) {
                $('#meteochart').html('<h2>No meteo data captured.</h2>');
            }
            else {   
	        	new Morris.Line({
	      		  // ID of the element in which to draw the chart.
	      		  element: 'meteochart',
	      		  // Chart data records -- each entry in this array corresponds to a point on
	      		  // the chart.
	      		  data: msg,
	      		  // The name of the data record attribute that contains x-values.
	      		  xkey: 'days',
	      		  // A list of names of data record attributes that contain y-values.
	      		  ykeys: ['love', 'health', 'money', 'mood'],
	      		  // Labels for the ykeys -- will be displayed when you hover over the
	      		  // chart.
	      		  labels: ['Love', 'Health', 'Money', 'Mood'],
	      		  lineColors: ['#F9A7B0	', '#00ADEF', 'lightgreen', 'yellow'],
	      		  hideHover: true,
	      		  parseTime: false
	      		});
	        	
	       	}
            updateNbSunnyDays();
        	updateNbRainyDays();
            $('.loading-indicator').removeClass('spin');
        	$('.loading-indicator').hide();
        },
        error: function(xhr, status, error) {
        	$('#meteochart').html(xhr.responseText);
        	$('.loading-indicator').removeClass('spin');
        	$('.loading-indicator').hide();
        }
    });
	
}
							
$(document).ready(function() {
	$( ".jscroll-inner" ).on( "click", ".accordion-toggle", function() {
		$(this).find("span").toggleClass('glyphicon-chevron-down glyphicon-chevron-up');
	});

	$( ".jscroll-inner" ).on( "mouseover", ".item", function() {
		$(this).css("background-color","#f2f1f0");
	});

	$( ".jscroll-inner" ).on( "mouseout", ".item", function() {
		$(this).css("background-color","white");
	});

	$('[data-ui="jscroll-default"]').jscroll({
		autoTrigger: false,
		debug: false,
		});

	updateNbCompletedTest();
	updateMeteoChart();
	
	//Destroy modal content after hiding
	$('body').on('hidden.bs.modal', '.modal', function () {
	    $(this).removeData('bs.modal').find(".modal-content").empty();
	    updateNbCompletedTest();
	    updateMeteoChart();
	});

	//record the sample 
	$( "#measurementmodal" ).on( "click", ".btn-meteo", function() {
		$('.btn-meteo').attr('disabled', 'disabled');
		$('.btn-default').attr('disabled', 'disabled');
        $.ajax({
            type: "GET",
            url: '/sensor/record/'+$(this).find('.sensorid').val()+'/'+$(this).find('.sampleid').val(), 
            cache: false,
            //data: $('form.sensor').serialize(),
            success: function(msg){
            	$("#measurementmodal").find('.modal-content').html(msg);
            	$('.btn-meteo').removeAttr("disabled");
            	$('.btn-default').removeAttr("disabled");
            },
            error: function(xhr, status, error) {
            	 $("#measurementmodal").find('#errormsg').html(xhr.responseText);
            	 $('.btn-meteo').removeAttr("disabled");
            	 $('.btn-default').removeAttr("disabled");
            }
        });
	});

	//sensor contribution form request
	$( "#sensor-contribution-button" ).on( "click", function(e) {
		e.preventDefault();
	//	$('#waitmodal').modal('show');
		$( "#sensormodal-content" ).load('/sensor/add', function( response, status, xhr ) {
			if ( status == "error" ) 
				$("#sensormodal").find('.modal-content').html(errorModal(xhr.responseText));
			//$('#waitmodal').modal('hide');
			$( "#sensormodal" ).modal('show');
			});
		$( "#sensormodal" ).modal('toggle');
	});

	//sensor test request
	$( "#sensor-test-button" ).on( "click", function(e) {
		e.preventDefault();
		$( "#measurementmodal-content" ).load('/sensor/get/random', function( response, status, xhr ) {
			if ( status == "error" ) 
				$("#measurementmodal").find('.modal-content').html(errorModal(xhr.responseText));
			$( "#measurementmodal" ).modal('show');
			});
		$( "#measurementmodal" ).modal('toggle');
	});

	//weather ananylse contribution form request
	$( "#anaylse-contribution-button" ).on( "click", function(e) {
		e.preventDefault();
		$( "#analysemodal-content" ).load($("#mindname").text()+'/add-analyse', function( response, status, xhr ) {
			if ( status == "error" ) 
				$("#analysemodal").find('.modal-content').html(errorModal(xhr.responseText));
			$( "#analysemodal" ).modal('show');
			});
		$( "#analysemodal" ).modal('toggle');
	});
	
	//skip the test
	$( "#measurementmodal" ).on( "click", ".skip", function() {
		$('.btn-meteo').attr('disabled', 'disabled');
		$('.btn-default').attr('disabled', 'disabled');
        $.ajax({
            type: "GET",
            url: '/sensor/get/random', 
            cache: false,
            success: function(msg){
            	$("#measurementmodal").find('.modal-content').html(msg);
            	$('.btn-meteo').removeAttr("disabled");
            	$('.btn-default').removeAttr("disabled");
            },
            error: function(xhr, status, error) {
            	 $("#measurementmodal").find('#errormsg').html(xhr.responseText);
            	 $('.btn-meteo').removeAttr("disabled");
            	 $('.btn-default').removeAttr("disabled");
            }
        });
	});

	//Activate the slider when the modal "sensor is loaded	
	$('body').on('show.bs.modal', '#sensormodal', function() {
		$(this).find('.slider').slider({ value : 0});

		$('form.sensor').bootstrapValidator({
			//submitButtons: 'input[name="submitsensor"]',
			submitHandler: function(validator, form, submitButton) {
				$.ajax({
			    	type: 'POST',
			        url: "/sensor/add", 
			        data: $(form).serialize(),
			        success: function(msg){
			           	$("#sensormodal").find('.modal-content').html(msg);
			        },
			        error: function(xhr, status, error) {
			           	 $("#sensormodal").find('#errormsg').html(xhr.responseText);
			           	 $('#submitsensor').removeAttr("disabled");
			        }
			    });
			    return false;
 			},
	    	feedbackIcons: {
	            valid: 'glyphicon glyphicon-ok',
	            invalid: 'glyphicon glyphicon-remove',
	            validating: 'glyphicon glyphicon-refresh'
	        },
	        fields: {
	        	label: {
	                message: 'The test of the sensor is not valid',
	                validators: {
	        			notEmpty: {
	            			message: 'Your test is required'
	        			},
	        			stringLength: {
	                        max: 128,
	                        message: 'Your test must be less than 128 characters'
	                    },
	                }
	            },
	            topic: {
	            	message: 'The topic of the sensor is not valid',
	                validators: {
		            	callback: {
							message : 'You should choose a topic',	
		                    callback: function(value, validator) {
			                    if (value == 'unpicked')
				                    return false;
			                    else
				                    return true;
		                    }
	                    },
	                }
		        },
		        answerPositive: {
		        	message: 'The positive sample is not valid',
	                validators: {
	                	notEmpty: {
	            			message: 'Your positive sample is required'
	        			},
	        			stringLength: {
	                        max: 32,
	                        message: 'Your positive sample must be less than 32 characters'
	                    },
	                    different: {
	                         field: 'answerNegative',
	                         message: "The negative and negative sample can't be the same"
	                     },
	                }
			    },
			    answerNegative: {
		        	message: 'The negative sample is not valid',
	                validators: {
	                	notEmpty: {
	            			message: 'Your negative sample is required'
	        			},
	        			stringLength: {
	                        max: 32,
	                        message: 'Your negative sample must be less than 32 characters'
	                    },
	                    different: {
	                         field: 'answerPositive',
	                         message: "The positive and negative sample can't be the same"
	                     },
	                }
			    },
			/*    answerPositiveValue: {
		        	message: 'The positive sample value is not valid',
	                validators: {
	                	 different: {
	                         field: 'answerNegativeValue',
	                         message: "The positive and negative sample can't have the same value"
	                     },
	                }
			    },
			    answerNegativeValue: {
		        	message: 'The negative sample value is not valid',
	                validators: {
	                	callback: {
							message : "The negative and positive sample can't have the same value",	
		                    callback: function(value, validator) {
			                    alert(value);
			                    if (value == $("#answerPositiveValue").getValue())
				                    return false;
			                    else
				                    return true;
		                    }
	                    },
	                	 different: {
	                         field: 'answerPositiveValue',
	                         message: "The negative and positive sample can't have the same value"
	                     },
	                }
			    },*/
	        }
	    });
		
	});
});
</script>
 
  
    

