<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
    <h4 class="modal-title" id="measurementModalLabel"><?php echo $this->escapeHtml('Record a measurement of your mind') ?></h4>
</div>
<div class="modal-body">
	<div id="errormsg"></div>
	<div id="sensortest" class="text-center" style="width: 100%; height: 100px; font-size: 20pt;"><?php echo $this->escapeHtml($sensor->getLabel()) ?></div>
	<div class="row">	
		 <div class="col-xs-6 text-center">	    
		 	
		 	<?php 
		 		if ($samplePos->getImg()) {
					echo '<span style="font-size: 14pt;">'.  $this->escapeHtml($samplePos->getLabel()) . '</span>';
					echo '<a href="#" class="thumbnail">';
					echo '<img src='.$samplePos()->getImg().'>';
					echo '</a>';
				}
				else {
					echo '<button class="btn btn-meteo" >'. $this->escapeHtml($samplePos->getLabel());// . "</button>";
					echo '<input type="hidden" class="sensorid" value="'. $sensor->getId(). '"/>';
					echo '<input type="hidden" class="sampleid" value="'. $samplePos->getId(). '"/>';
					echo "</button>";
				}
		 	?>
	    	
	    </div>
	     <div class="col-xs-6 text-center">	   
	     	<?php 
		 		if ($sampleNeg->getImg()) {
					echo '<span style="font-size: 14pt;">'.  $this->escapeHtml($sampleNeg->getLabel()) . '</span>';
					echo '<a href="#" class="thumbnail">';
					echo '<img src='.$sampleNeg()->getImg().'>';
					echo '</a>';
				}
				else {
					echo '<button class="btn btn-meteo" >'. $this->escapeHtml($sampleNeg->getLabel());// . "</button>";
					echo '<input type="hidden" class="sensorid" value="'. $sensor->getId(). '"/>';
					echo '<input type="hidden" class="sampleid" value="'. $sampleNeg->getId(). '"/>';
					echo "</button>";
				}
		 	?>
	    		
	    </div>
	</div>
</div>
<div class="modal-footer">
	<button type='button' class='btn btn-default' data-dismiss='modal'>Leave me now</button>
</div>
