<?php echo $this->doctype(); ?>

<html lang="en" ng-app="mindmeteo">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Mind Meteo administration'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', /*'href' => $this->basePath() . '/img/favicon.ico'*/))
        				//->prependStylesheet($this->basePath() . '/css/bootstrap-modal-bs3patch.css')
        				->prependStylesheet($this->basePath() . '/css/main.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/mindmeteo.css')
                        ->prependStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css')
                        ->prependStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css')
        				 ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
           // ->prependFile('//code.jquery.com/jquery-migrate-1.2.1.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile('/js/adminController.js')
            ->prependFile('/js/adminServices.js')
            ->prependFile('/js/adminDirectives.js')
            ->prependFile('/js/app.js')
            ->prependFile('/js/bower_components/angular-google-chart/ng-google-chart.js')
            ->prependFile('/js/bower_components/ng-table/ng-table.js')
            ->prependFile('http://code.angularjs.org/1.2.8/angular-resource.min.js')
            ->prependFile('http://code.angularjs.org/1.2.8/angular-route.min.js')
            ->prependFile('https://ajax.googleapis.com/ajax/libs/angularjs/1.2.8/angular.min.js')
            ->prependFile('//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js')
            ->prependFile('//code.jquery.com/jquery-1.11.0.min.js')
        ; ?>
    </head>
    <body>
        <div class="container">
			<?php echo $this->partial('partials/navbar-admin.phtml'); ?>
			<div class="row">
				<div class="col-lg-2">
					<?php echo $this->partial('partials/menu-admin.phtml'); ?>
				</div>
				<div ng-view></div>
			</div>
            <hr>
            <footer>
                <p>&copy; developped by devitito</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
