<?php echo $this->doctype(); ?>

<html lang="en" ng-app="mindmeteo">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Welcome to the meteo of your mind'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', /*'href' => $this->basePath() . '/img/favicon.ico'*/))
        				//->prependStylesheet($this->basePath() . '/css/bootstrap-modal-bs3patch.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/mindmeteo.css')
                        ->prependStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css')
                        ->prependStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css')
        				 ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile('//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js')
            ->prependFile('//code.jquery.com/jquery-1.11.0.min.js')
            ->prependFile('//code.jquery.com/jquery-migrate-1.2.1.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile('https://ajax.googleapis.com/ajax/libs/angularjs/1.2.25/angular.min.js')
        ; ?>
    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; developped by devitito</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
