<?php echo $this->partial('partials/navbar-admin.phtml'); ?>

<div class="container">
	<div class="row">
		<div class="col-lg-2">
			<?php echo $this->partial('partials/menu-admin.phtml'); ?>
		</div>
		<div class="col-lg-10">
			<p>create mind form</p>
			<a href="#" type="button" class="btn btn-meteo"><?php echo $this->translate('Save') ?></a>
			<a href="/administrator/minds" type="button" class="btn btn-default"><?php echo $this->translate('Cancel') ?></a>
		</div>
	</div>
</div>