<div class="col-lg-10" ng-controller="mindsCtrl">
	<a href="minds/new" type="button" class="btn btn-meteo">Create a mind</a>
	<br><br>
	<p>list of minds update/delete/view</p>
	
	<div>
		<table id="mindlist" class="table">
			<thead>
		        <tr>
		          <th>Name</th>
		          <th>Join Date</th>
		          <th>Role</th>
		        </tr>
		      </thead>
		      <tbody>
				<tr ng-repeat="mind in minds">
					<td>{{mind.name}}</td>
					<td>{{mind.joindate}}</td>
					<td>{{mind.role}}</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
