<?php echo $this->partial('partials/navbar-admin.phtml'); ?>

<div class="container">
	<div class="row">
		<div class="col-lg-2">
			<?php echo $this->partial('partials/menu-admin.phtml'); ?>
		</div>
		<div class="col-lg-10">
			<button type="button" class="btn btn-meteo">Create a mind</button>
			<p>list of minds update/delete/view</p>
			
			<div>
			<table>
				<tr>
					<td>mind1</td>
				</tr>
				
			</table>
			</div>
		</div>
	</div>
</div>

<script>

</script>
 
  
    

