<?php echo $this->partial('partials/navbar-admin.phtml'); ?>

<div class="container">
	<div class="row">
		<div class="col-lg-2">
			<?php echo $this->partial('partials/menu-admin.phtml'); ?>
		</div>
		<div class="col-lg-10">
			<header><p>sensors</p></header>
			<p>list of sensors (approved, to be approved)</p>
			<p>Delegate approval to a validator</p>
		</div>
	</div>
</div>

<script>

</script>
 
  
    

