<?php echo $this->partial('partials/navbar-admin.phtml'); ?>

<div class="container">
	<div class="row">
		<div class="col-lg-2">
			<?php echo $this->partial('partials/menu-admin.phtml'); ?>
		</div>
		<div class="col-lg-10">
			<header><p>stats</p></header>
			<p>Most popular test</p>
			<p>Most skipped test</p>
			<p>Time of test 00 till 23</p>
			<p>Days of tests monday till sunday</p>
		</div>
	</div>
</div>

<script>

</script>
 
  
    

