<!-- Le styles -->
 <?php echo $this->headLink()
 				->prependStylesheet($this->basePath() . '/btvalidator/dist/css/bootstrapValidator.min.css')
 ?>

<!-- Scripts -->
<?php echo $this->headScript()
        		->prependFile($this->basePath() . '/btvalidator/dist/js/bootstrapValidator.min.js')
        		->prependFile($this->basePath() . '/js/formsValidator.js');
?>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" action="/login" method="post" accept-charset="UTF-8">
            <div class="form-group">
              <input type="text" placeholder="Mind or Email" class="form-control" name="nameoremail">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control" name="password">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </div>

<div class="jumbotron">
       
    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-8">
			<h1><?php echo sprintf($this->translate('Welcome to the meteo of your mind'), '<span class="zf-green">', '</span>') ?></h1>
  			<p><?php echo sprintf($this->translate('More coming soon!!!')) ?></p>
        </div>
        <div class="col-md-4">
        <?php echo $this->partial('partials/quickRegistration', ['form' => $form]); ?>
        </div>
      </div>
	</div>
</div>

<script>
$(document).ready(validateQuickRegistration($));
</script>