<!-- Le styles -->
 <?php echo $this->headLink()
 				->prependStylesheet($this->basePath() . '/btvalidator/dist/css/bootstrapValidator.min.css')
 ?>

<!-- Scripts -->
<?php echo $this->headScript()
        		->prependFile($this->basePath() . '/btvalidator/dist/js/bootstrapValidator.min.js')
        		->prependFile($this->basePath() . '/js/formsValidator.js')
?>

<h1><?php echo $this->escapeHtml('Join in') ?></h1>
<div class="jumbotron">
    
    <div class="container">
<?php 
  if ($this->flashmessenger()->hasCurrentErrorMessages()) {
	$messages = $this->flashmessenger()->getCurrentErrorMessages();
  	foreach ($messages as $message)
  	{
  		echo  '<div class="alert alert-danger" role="alert">';
		echo $message;
    	echo '</div>';
  	}
  	$this->flashmessenger()->clearCurrentMessages();
  }
?>      
      <div class="row">
      	<div class="col-md-4">
        </div>
        <div class="col-md-4">
        <?php echo $this->partial('partials/quickRegistration', ['form' => $form]); ?>
<div class="col-md-4"></div>
</div>
</div>
</div>
</div>

<script>
$(document).ready(validateQuickRegistration($));
</script>