<h1><?php echo $this->escapeHtml('Sign in') ?></h1>
<div class="jumbotron">
    
    <div class="container">
<?php 
  if ($this->flashmessenger()->hasCurrentErrorMessages()) {
	$messages = $this->flashmessenger()->getCurrentErrorMessages();
  	foreach ($messages as $message)
  	{
  		echo  '<div class="alert alert-danger" role="alert">';
		echo $message;
    	echo '</div>';
  	}
  	$this->flashmessenger()->clearCurrentMessages();
  }
?>      
      <div class="row">
      	<div class="col-md-4">
        </div>
        <div class="col-md-4">
<?php

echo $this->form()->openTag($form);
$this->formElementErrors()
	->setMessageOpenFormat('<div class="alert alert-danger">')
	->setMessageSeparatorString('')
	->setMessageCloseString('</div>');

foreach ($form as $element) {
    if ($element->getOption('label')) echo $this->formLabel($element);
    echo '<div class="form-group">';
	echo $this->formElement($element);
	echo '</div>';
    //echo $this->formElementErrors($element);
}

echo $this->form()->closeTag(); // </form>

?>
<div class="col-md-4"></div>
</div>
</div>
</div>
</div>