<!-- Le styles -->
 <?php echo $this->headLink()
 				->prependStylesheet($this->basePath() . '/btvalidator/dist/css/bootstrapValidator.min.css')
 ?>

<!-- Scripts -->
<?php echo $this->headScript()
        		->prependFile($this->basePath() . '/btvalidator/dist/js/bootstrapValidator.min.js')
        		->prependFile($this->basePath() . '/js/formsValidator.js')
?>

<?php echo $this->partial('partials/navbar-logged-out'); ?>

<br>

<div class="container">
	<?php 
	  if ($this->flashmessenger()->hasCurrentErrorMessages()) {
		$messages = $this->flashmessenger()->getCurrentErrorMessages();
	  	foreach ($messages as $message)
	  	{
	  		echo  '<div class="alert alert-danger" role="alert">';
			echo $message;
	    	echo '</div>';
	  	}
	  	$this->flashmessenger()->clearCurrentMessages();
	  }
	?>      
	<div class="row">
  		<div class="col-md-4">
    	</div>
	    <div class="col-md-4">
			<table class="table table-bordered">
				<tr><th style="background: #00ADEF;	color: #FFFFFF; "><?php echo $this->escapeHtml('Sign in') ?></th></tr>
				<tr>
					<td>
						<?php
							echo $this->form()->openTag($form);
							foreach ($form as $element) {
							    if ($element->getOption('label')) echo $this->formLabel($element);
							    echo '<div class="form-group">';
								echo $this->formElement($element);
								echo '</div>';
							    //echo $this->formElementErrors($element);
							}
							echo $this->form()->closeTag(); // </form>
						?>
					</td>
				</tr>
			</table>
		</div>
		<div class="col-md-4"></div>
	</div>
</div>